### ISSUE TITLE
how to add links to html?

### ISSUE THREAD

**Issue by nikbelikov** [Creatiwity/gatsby-plugin-favicon#4] opened 2017-10-31 09:49 UTC
The plugin adds _favicons_ folder to **public** folder. But there is no any links to that icons in index.html. How can i add them?

**Comment by mperkh** [comment] 2017-10-31 10:54
There is already a pull request https://github.com/Creatiwity/gatsby-plugin-favicon/pull/2.

@julien1619 is there anything we could do, to bring wind into this issue https://github.com/Creatiwity/gatsby-plugin-favicon/issues/1?

**Comment by julien1619** [comment] 2017-10-31 15:16
Thank you for the reminder! I've juste merged it. So html injection is done by the plugin.

**Comment by nikbelikov** [comment] 2017-11-13 13:48
I've updated package and can't see any changes. There is no any links to favicons in result compressed html.

**Comment by chadwatson** [comment] 2017-11-28 02:55
This doesn't appear to be working for me either. Using `2.0.0` on two different sites with no success.

[https://www.417tubs.com/](https://www.417tubs.com/)
[https://suspicious-noyce-c14778.netlify.com/](https://suspicious-noyce-c14778.netlify.com/)

Here is my `gatsby-config.js`:

```javascript
const siteMetadata = require('./data')

module.exports = {
  siteMetadata,
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-transformer-sharp',
    'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-favicon',
      options: {
        logo: './src/favicon.png',
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          favicons: true,
          firefox: true,
          twitter: true,
          windows: true,
        },
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${process.cwd()}/src/pages`,
        name: 'pages'
      }
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 800,
              linkImagesToOriginal: false
            }
          }
        ]
      }
    }
  ],
}
```

**Comment by mperkh** [comment] 2017-11-28 08:38
Current v2.0.0 of this plugin is broken and does not inject html. Pull request https://github.com/Creatiwity/gatsby-plugin-favicon/pull/6, which fixes the problem is here and waiting to be processes by the project owner.

In the meantime, please use a temporary version of the plugin, which covers the mentioned fixes.

`npm remove gatsby-plugin-favicon`
`npm install gatsby-plugin-favicon-mperkh`

also use the corresponding plugin name in `gatsby-config.js`:

```resolve: `gatsby-plugin-favicon-mperkh`,```

**Comment by julien1619** [comment] 2017-11-30 16:40
@nikbelikov @chadwatson A new version is available which should fix everything, can you confirm that it's working now? Thanks!

**Comment by nikbelikov** [comment] 2017-12-01 18:57
It works well. Thank you!

**Closed as completed** 2017-12-04 06:51 UTC
