### ISSUE TITLE
Check if file has changed before generating favicons

### ISSUE THREAD

**Issue by Undistraction** [Creatiwity/gatsby-plugin-favicon#9] opened 2017-11-08 17:50 UTC
Looks like this plugin is generating every favicon every time it runs, regardless of whether the source icon has changed. Given how long image generation takes, this is a bit of a deal breaker. 

Please perform a check to see if the source image has changed and if not, skip favicon generation.

**Comment by mperkh** [comment] 2017-11-08 21:27
hmm.. https://github.com/jantimon/favicons-webpack-plugin/blob/master/README.md `persistentCache` defaults to `true`, so this gatsbyJS plugin always also creates a `.cache` file, which contains hash for `logo.png` and options.
Just tried it and it seems to work, the webpack plugin does not regenerate icons, if logo.png or options do not change.

```js
// Generate a cache file with control hashes and
// don't rebuild the favicons until those hashes change
persistentCache: true,
```

Can you supply a way to reproduce the issue?

**Comment by Undistraction** [comment] 2017-11-08 22:28
Sure: If you pull this: https://github.com/Undistraction/gatsby-skeleton

- `yarn`
- `yarn run dev`
- You'll see the build hang during the favicon image processing.
- Cancel out and run again and you'll see the same hang, despite the fact the favicons have been generated already.
- Remove the plugin and rerun and you won't see that hang. 

I'm on OSX 0.11.6 btw.

**Comment by mperkh** [comment] 2017-11-09 11:28
Can confirm, build times are 10 times higher, with this plugin activated. Not sure, if this is an issue with https://github.com/jantimon/favicons-webpack-plugin and where the fix is needed.

![favicon](https://user-images.githubusercontent.com/1648040/32603251-51423f76-c549-11e7-9e02-a12a2210d60f.png)

PS: Seems to be an issue with combination of gatsbyJS and favicons-webpack-plugin. favicons-webpack-plugin seems to work correctly.

**Comment by julien1619** [comment] 2017-11-30 15:48
It should be fixed by #6, thank you @mperkh and @Undistraction for the report!

**Closed as completed by julien1619** 2017-11-30 15:48 UTC

**Comment by Undistraction** [comment] 2017-11-30 16:52
Nicely done. I'll give it a good check tomorrow.

**Comment by Undistraction** [comment] 2017-12-13 01:07
This is working nicely now. Thanks. 

You should add this plugin to Gatsby's list of community plugins: https://www.gatsbyjs.org/docs/plugins/
